service: github-ranking-for-gsm
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
  stage: api

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
    GatewayResponseDefault5XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: "ApiGatewayRestApi"

functions:
  graphql:
    handler: app.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
  auth:
    handler: auth.authUserByOAuth
    events:
      - http:
          path: auth
          method: get
          cors: false
  email_auth:
    handler: auth.authUserByEmail
    events:
      - http:
          path: email/{token}
          method: get
          cors: false
  send_email:
    handler: auth.authEmail
    events:
      - http:
          path: send-email
          method: post
          cors: false
package:
  patterns:
    - "!node_modules/**/query-engine-**"
    - "!node_modules/@prisma/engines/**"
    - node_modules/.prisma/client/query-engine-rhel-*
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
