name: Update
on:
  schedule:
    - cron: "0 18 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn

      - name: User information update
        run: yarn delete
        env:
          MongoDBUrl: ${{ secrets.MONGODBURL }}
