name: Push gh-pages
on:
  push:
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install
        run: yarn install
        
      - name: compile graphdoc
        run: yarn graphdoc -e https://d6ui2fy5uj.execute-api.ap-northeast-2.amazonaws.com/api/graphql -o ./docs

      - name: merge page and docs
        run: cp -r page/* docs/

      - name: deploy gh-pages
        uses: peaceiris/actions-gh-pages@v2.5.0
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./docs
        
        
