name: Update
on:
  schedule:
    - cron: "0 18 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: yarn install
      - name: Delete dist
        run: rm -rf dist

      - name: Typescript compile
        run: ./node_modules/.bin/tsc

      - name: User information update
        run: yarn update
